[user]
name = "MVA"
email = "mva000@gmail.com"

[ui]
ui.color = "auto" # the default
# ui.color = never # no color

# editor = ["C:\\Program Files\\Git\\usr\\bin\\vim.exe", "--literal"]
editor = ["D:/progs/sakura-x64/sakura.exe"]
pager=["C:/Program Files/Git/usr/bin/less.exe", "-FRX"]
paginate = "auto"

ui.diff-editor = ":builtin" # default, internal TUI tool
# ui.diff-editor = "meld"
# ui.diff-editor = "vimdiff"

# ui.merge-editor = "meld" # default
ui.merge-editor = "vscode"
# ui.merge-editor = "vimdiff"
# ui.merge-editor = "kdiff3"

[alias]
alog=["log", "-r", "..@"]
clog=["log", "-T", "builtin_log_comfortable"]
calog=["log", "-r", "..@", "-T", "builtin_log_comfortable"]
dlog=["log", "-T", "builtin_log_detailed"]
dalog=["log", "-r", "..@", "-T", "builtin_log_detailed"]
olog=["log", "-T", "builtin_log_oneline"]
oalog=["log", "-r", "..@", "-T", "builtin_log_oneline"]

# Change the default push/fetch remote for `jj git push` and `jj git fetch`
# git.fetch = "upstream"
# git.push = "myfork"

#
# source <(jj util completion bash)
#
# jj git init
# jj git remote add origin <URL>
# jj branch create -r @- main
#
# jj git init --colocate
#
# jj branch set -r @- main
#
# jj squash --from aaa:: --into bbb
